### PR TITLE
1. Added automatic price calculating and ..

### PR DESCRIPTION
**Pull request by kiteretsu-daihyakka**
2. Updated page design via the following changes:
-removed item name and item price labels
-item price will be right-aligned when entered
-generate pdf button will take full page width in a smaller device
-total price badge will take full page width in a smaller device
-removed /- from the total price

### CODE REVIEW

**Comment by SireenAtGitHub** [comment]
image
A number over here feels lonely. How about we put it it like ITEM 1, ITEM 2, ITEM 3....?

**Comment by SireenAtGitHub** [comment]
These new changes are **lit** by the way.

**Comment by kiteretsu-daihyakka** [comment]
Okay, sure, let me add the item 1 instead of only 1.

**Comment by SireenAtGitHub** [comment]
> Okay, sure, let me add the item 1 instead of only 1.

Should I close the current PR?

**Comment by SireenAtGitHub** [comment]
I made the change and I'm merging it.

**Comment by SireenAtGitHub** [comment]
It's in production now. 

@kiteretsu-daihyakka

**Pull request merged**
